// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqxvvjdegwukvvrefkho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxeHZ2amRlZ3d1a3Z2cmVma2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNDA1NzgsImV4cCI6MjA1MTkxNjU3OH0.JuAOYKeyQvdId-bEMvPRgShYGDGXNe06Hxe4NBXeFOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);